server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/projectmanagement
    password: postgres
  jpa:
    #to-do: think if it needs
    open-in-view: 'true'
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
  security:
    origins:
      allow: '*'

  flyway:
    url: jdbc:postgresql://localhost:5432/projectmanagement
    user: postgres
    password: postgres
    baseline-on-migrate: true
    locations: '/db/common,/db/test'
    check-location: false

authentication:
  jwt:
    header: "Authorization"
    prefix: "Bearer"
    secret: "golosanswers2jwt"
    lifeTime: 600000
    range: 120
    responseHeader: "Access-Token"
